# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rhacker/Dokumenty/RedCraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rhacker/Dokumenty/RedCraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhacker/Dokumenty/RedCraft/CMakeFiles /home/rhacker/Dokumenty/RedCraft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhacker/Dokumenty/RedCraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RedCraft

# Build rule for target.
RedCraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RedCraft
.PHONY : RedCraft

# fast build rule for target.
RedCraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/build
.PHONY : RedCraft/fast

src/core/Game.o: src/core/Game.cpp.o
.PHONY : src/core/Game.o

# target to build an object file
src/core/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Game.cpp.o
.PHONY : src/core/Game.cpp.o

src/core/Game.i: src/core/Game.cpp.i
.PHONY : src/core/Game.i

# target to preprocess a source file
src/core/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Game.cpp.i
.PHONY : src/core/Game.cpp.i

src/core/Game.s: src/core/Game.cpp.s
.PHONY : src/core/Game.s

# target to generate assembly for a file
src/core/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Game.cpp.s
.PHONY : src/core/Game.cpp.s

src/core/Voxelium.o: src/core/Voxelium.cpp.o
.PHONY : src/core/Voxelium.o

# target to build an object file
src/core/Voxelium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Voxelium.cpp.o
.PHONY : src/core/Voxelium.cpp.o

src/core/Voxelium.i: src/core/Voxelium.cpp.i
.PHONY : src/core/Voxelium.i

# target to preprocess a source file
src/core/Voxelium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Voxelium.cpp.i
.PHONY : src/core/Voxelium.cpp.i

src/core/Voxelium.s: src/core/Voxelium.cpp.s
.PHONY : src/core/Voxelium.s

# target to generate assembly for a file
src/core/Voxelium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/Voxelium.cpp.s
.PHONY : src/core/Voxelium.cpp.s

src/core/gameCreator.o: src/core/gameCreator.cpp.o
.PHONY : src/core/gameCreator.o

# target to build an object file
src/core/gameCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/gameCreator.cpp.o
.PHONY : src/core/gameCreator.cpp.o

src/core/gameCreator.i: src/core/gameCreator.cpp.i
.PHONY : src/core/gameCreator.i

# target to preprocess a source file
src/core/gameCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/gameCreator.cpp.i
.PHONY : src/core/gameCreator.cpp.i

src/core/gameCreator.s: src/core/gameCreator.cpp.s
.PHONY : src/core/gameCreator.s

# target to generate assembly for a file
src/core/gameCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/gameCreator.cpp.s
.PHONY : src/core/gameCreator.cpp.s

src/core/worldGen.o: src/core/worldGen.cpp.o
.PHONY : src/core/worldGen.o

# target to build an object file
src/core/worldGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/worldGen.cpp.o
.PHONY : src/core/worldGen.cpp.o

src/core/worldGen.i: src/core/worldGen.cpp.i
.PHONY : src/core/worldGen.i

# target to preprocess a source file
src/core/worldGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/worldGen.cpp.i
.PHONY : src/core/worldGen.cpp.i

src/core/worldGen.s: src/core/worldGen.cpp.s
.PHONY : src/core/worldGen.s

# target to generate assembly for a file
src/core/worldGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/core/worldGen.cpp.s
.PHONY : src/core/worldGen.cpp.s

src/gui/gui.o: src/gui/gui.cpp.o
.PHONY : src/gui/gui.o

# target to build an object file
src/gui/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/gui.cpp.o
.PHONY : src/gui/gui.cpp.o

src/gui/gui.i: src/gui/gui.cpp.i
.PHONY : src/gui/gui.i

# target to preprocess a source file
src/gui/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/gui.cpp.i
.PHONY : src/gui/gui.cpp.i

src/gui/gui.s: src/gui/gui.cpp.s
.PHONY : src/gui/gui.s

# target to generate assembly for a file
src/gui/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/gui.cpp.s
.PHONY : src/gui/gui.cpp.s

src/gui/inventory.o: src/gui/inventory.cpp.o
.PHONY : src/gui/inventory.o

# target to build an object file
src/gui/inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/inventory.cpp.o
.PHONY : src/gui/inventory.cpp.o

src/gui/inventory.i: src/gui/inventory.cpp.i
.PHONY : src/gui/inventory.i

# target to preprocess a source file
src/gui/inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/inventory.cpp.i
.PHONY : src/gui/inventory.cpp.i

src/gui/inventory.s: src/gui/inventory.cpp.s
.PHONY : src/gui/inventory.s

# target to generate assembly for a file
src/gui/inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/inventory.cpp.s
.PHONY : src/gui/inventory.cpp.s

src/gui/loading.o: src/gui/loading.cpp.o
.PHONY : src/gui/loading.o

# target to build an object file
src/gui/loading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/loading.cpp.o
.PHONY : src/gui/loading.cpp.o

src/gui/loading.i: src/gui/loading.cpp.i
.PHONY : src/gui/loading.i

# target to preprocess a source file
src/gui/loading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/loading.cpp.i
.PHONY : src/gui/loading.cpp.i

src/gui/loading.s: src/gui/loading.cpp.s
.PHONY : src/gui/loading.s

# target to generate assembly for a file
src/gui/loading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/loading.cpp.s
.PHONY : src/gui/loading.cpp.s

src/gui/menu.o: src/gui/menu.cpp.o
.PHONY : src/gui/menu.o

# target to build an object file
src/gui/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/menu.cpp.o
.PHONY : src/gui/menu.cpp.o

src/gui/menu.i: src/gui/menu.cpp.i
.PHONY : src/gui/menu.i

# target to preprocess a source file
src/gui/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/menu.cpp.i
.PHONY : src/gui/menu.cpp.i

src/gui/menu.s: src/gui/menu.cpp.s
.PHONY : src/gui/menu.s

# target to generate assembly for a file
src/gui/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui/menu.cpp.s
.PHONY : src/gui/menu.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/resources/textures.o: src/resources/textures.cpp.o
.PHONY : src/resources/textures.o

# target to build an object file
src/resources/textures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/resources/textures.cpp.o
.PHONY : src/resources/textures.cpp.o

src/resources/textures.i: src/resources/textures.cpp.i
.PHONY : src/resources/textures.i

# target to preprocess a source file
src/resources/textures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/resources/textures.cpp.i
.PHONY : src/resources/textures.cpp.i

src/resources/textures.s: src/resources/textures.cpp.s
.PHONY : src/resources/textures.s

# target to generate assembly for a file
src/resources/textures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/resources/textures.cpp.s
.PHONY : src/resources/textures.cpp.s

src/utils/client.o: src/utils/client.cpp.o
.PHONY : src/utils/client.o

# target to build an object file
src/utils/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/client.cpp.o
.PHONY : src/utils/client.cpp.o

src/utils/client.i: src/utils/client.cpp.i
.PHONY : src/utils/client.i

# target to preprocess a source file
src/utils/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/client.cpp.i
.PHONY : src/utils/client.cpp.i

src/utils/client.s: src/utils/client.cpp.s
.PHONY : src/utils/client.s

# target to generate assembly for a file
src/utils/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/client.cpp.s
.PHONY : src/utils/client.cpp.s

src/utils/discord.o: src/utils/discord.cpp.o
.PHONY : src/utils/discord.o

# target to build an object file
src/utils/discord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/discord.cpp.o
.PHONY : src/utils/discord.cpp.o

src/utils/discord.i: src/utils/discord.cpp.i
.PHONY : src/utils/discord.i

# target to preprocess a source file
src/utils/discord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/discord.cpp.i
.PHONY : src/utils/discord.cpp.i

src/utils/discord.s: src/utils/discord.cpp.s
.PHONY : src/utils/discord.s

# target to generate assembly for a file
src/utils/discord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/discord.cpp.s
.PHONY : src/utils/discord.cpp.s

src/utils/logging.o: src/utils/logging.cpp.o
.PHONY : src/utils/logging.o

# target to build an object file
src/utils/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/logging.cpp.o
.PHONY : src/utils/logging.cpp.o

src/utils/logging.i: src/utils/logging.cpp.i
.PHONY : src/utils/logging.i

# target to preprocess a source file
src/utils/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/logging.cpp.i
.PHONY : src/utils/logging.cpp.i

src/utils/logging.s: src/utils/logging.cpp.s
.PHONY : src/utils/logging.s

# target to generate assembly for a file
src/utils/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/logging.cpp.s
.PHONY : src/utils/logging.cpp.s

src/utils/settings.o: src/utils/settings.cpp.o
.PHONY : src/utils/settings.o

# target to build an object file
src/utils/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/settings.cpp.o
.PHONY : src/utils/settings.cpp.o

src/utils/settings.i: src/utils/settings.cpp.i
.PHONY : src/utils/settings.i

# target to preprocess a source file
src/utils/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/settings.cpp.i
.PHONY : src/utils/settings.cpp.i

src/utils/settings.s: src/utils/settings.cpp.s
.PHONY : src/utils/settings.s

# target to generate assembly for a file
src/utils/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/utils/settings.cpp.s
.PHONY : src/utils/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RedCraft"
	@echo "... src/core/Game.o"
	@echo "... src/core/Game.i"
	@echo "... src/core/Game.s"
	@echo "... src/core/Voxelium.o"
	@echo "... src/core/Voxelium.i"
	@echo "... src/core/Voxelium.s"
	@echo "... src/core/gameCreator.o"
	@echo "... src/core/gameCreator.i"
	@echo "... src/core/gameCreator.s"
	@echo "... src/core/worldGen.o"
	@echo "... src/core/worldGen.i"
	@echo "... src/core/worldGen.s"
	@echo "... src/gui/gui.o"
	@echo "... src/gui/gui.i"
	@echo "... src/gui/gui.s"
	@echo "... src/gui/inventory.o"
	@echo "... src/gui/inventory.i"
	@echo "... src/gui/inventory.s"
	@echo "... src/gui/loading.o"
	@echo "... src/gui/loading.i"
	@echo "... src/gui/loading.s"
	@echo "... src/gui/menu.o"
	@echo "... src/gui/menu.i"
	@echo "... src/gui/menu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/resources/textures.o"
	@echo "... src/resources/textures.i"
	@echo "... src/resources/textures.s"
	@echo "... src/utils/client.o"
	@echo "... src/utils/client.i"
	@echo "... src/utils/client.s"
	@echo "... src/utils/discord.o"
	@echo "... src/utils/discord.i"
	@echo "... src/utils/discord.s"
	@echo "... src/utils/logging.o"
	@echo "... src/utils/logging.i"
	@echo "... src/utils/logging.s"
	@echo "... src/utils/settings.o"
	@echo "... src/utils/settings.i"
	@echo "... src/utils/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

