# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rhacker/Dokumenty/RedCraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rhacker/Dokumenty/RedCraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhacker/Dokumenty/RedCraft/CMakeFiles /home/rhacker/Dokumenty/RedCraft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhacker/Dokumenty/RedCraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RedCraft

# Build rule for target.
RedCraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RedCraft
.PHONY : RedCraft

# fast build rule for target.
RedCraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/build
.PHONY : RedCraft/fast

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Voxelium.o: src/Voxelium.cpp.o
.PHONY : src/Voxelium.o

# target to build an object file
src/Voxelium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Voxelium.cpp.o
.PHONY : src/Voxelium.cpp.o

src/Voxelium.i: src/Voxelium.cpp.i
.PHONY : src/Voxelium.i

# target to preprocess a source file
src/Voxelium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Voxelium.cpp.i
.PHONY : src/Voxelium.cpp.i

src/Voxelium.s: src/Voxelium.cpp.s
.PHONY : src/Voxelium.s

# target to generate assembly for a file
src/Voxelium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/Voxelium.cpp.s
.PHONY : src/Voxelium.cpp.s

src/gameCreator.o: src/gameCreator.cpp.o
.PHONY : src/gameCreator.o

# target to build an object file
src/gameCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gameCreator.cpp.o
.PHONY : src/gameCreator.cpp.o

src/gameCreator.i: src/gameCreator.cpp.i
.PHONY : src/gameCreator.i

# target to preprocess a source file
src/gameCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gameCreator.cpp.i
.PHONY : src/gameCreator.cpp.i

src/gameCreator.s: src/gameCreator.cpp.s
.PHONY : src/gameCreator.s

# target to generate assembly for a file
src/gameCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gameCreator.cpp.s
.PHONY : src/gameCreator.cpp.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/inventory.o: src/inventory.cpp.o
.PHONY : src/inventory.o

# target to build an object file
src/inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/inventory.cpp.o
.PHONY : src/inventory.cpp.o

src/inventory.i: src/inventory.cpp.i
.PHONY : src/inventory.i

# target to preprocess a source file
src/inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/inventory.cpp.i
.PHONY : src/inventory.cpp.i

src/inventory.s: src/inventory.cpp.s
.PHONY : src/inventory.s

# target to generate assembly for a file
src/inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/inventory.cpp.s
.PHONY : src/inventory.cpp.s

src/loading.o: src/loading.cpp.o
.PHONY : src/loading.o

# target to build an object file
src/loading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/loading.cpp.o
.PHONY : src/loading.cpp.o

src/loading.i: src/loading.cpp.i
.PHONY : src/loading.i

# target to preprocess a source file
src/loading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/loading.cpp.i
.PHONY : src/loading.cpp.i

src/loading.s: src/loading.cpp.s
.PHONY : src/loading.s

# target to generate assembly for a file
src/loading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/loading.cpp.s
.PHONY : src/loading.cpp.s

src/logging.o: src/logging.cpp.o
.PHONY : src/logging.o

# target to build an object file
src/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/logging.cpp.o
.PHONY : src/logging.cpp.o

src/logging.i: src/logging.cpp.i
.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/logging.cpp.i
.PHONY : src/logging.cpp.i

src/logging.s: src/logging.cpp.s
.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/logging.cpp.s
.PHONY : src/logging.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/perlinNoise.o: src/perlinNoise.cpp.o
.PHONY : src/perlinNoise.o

# target to build an object file
src/perlinNoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/perlinNoise.cpp.o
.PHONY : src/perlinNoise.cpp.o

src/perlinNoise.i: src/perlinNoise.cpp.i
.PHONY : src/perlinNoise.i

# target to preprocess a source file
src/perlinNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/perlinNoise.cpp.i
.PHONY : src/perlinNoise.cpp.i

src/perlinNoise.s: src/perlinNoise.cpp.s
.PHONY : src/perlinNoise.s

# target to generate assembly for a file
src/perlinNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/perlinNoise.cpp.s
.PHONY : src/perlinNoise.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RedCraft.dir/build.make CMakeFiles/RedCraft.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RedCraft"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Voxelium.o"
	@echo "... src/Voxelium.i"
	@echo "... src/Voxelium.s"
	@echo "... src/gameCreator.o"
	@echo "... src/gameCreator.i"
	@echo "... src/gameCreator.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/inventory.o"
	@echo "... src/inventory.i"
	@echo "... src/inventory.s"
	@echo "... src/loading.o"
	@echo "... src/loading.i"
	@echo "... src/loading.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/perlinNoise.o"
	@echo "... src/perlinNoise.i"
	@echo "... src/perlinNoise.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

